config/routes.rb
Rails.application.routes.draw do

  #orders routes
  resources :orders do
    resources:orderitems
  end
    get '/shipped/:id' => 'orders#shipped'
  
  
  #user routes
  devise_for :users do
    resources:orders
  end
  
  devise_for :controllers => {
   :registration => "users/registration",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmation => "users/confriamtions" }
  devise_scope :users do
    get 'signup', to: 'users/regisatrations#new'
    get 'signin', to: 'users/session#new'
    delete 'signout', to: 'users/session#destroy'
 
  end
  
  post '/search' => 'items#search'
  get '/search' => 'items#search'
  post '/filter' => 'items#filter'
  get '/filter' => 'items#filter'
  
  resources :items do
    resources :reviews
  end
  
  
  
  #static page roots
  root 'static_pages#home'
  
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/delivery' => 'static_pages#delivery'
 
  
  #cart routes
  #get 'cart/index'
 
  get '/cart' => 'cart#index'
  
  get '/cart/clear' => 'cart#clear'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/updatequantity/:id' => 'cart#update_quantity'
  get '/cart/addbyquantity/:id' => 'cart#add_by_quantity'
  get '/cart/fromwishlist/:id' => 'cart#add_from_wishlist'

  get '/checkout' => 'cart#create_order'
  post '/checkout' => 'cart#create_order'
  get '/checkout/complete' => 'orders#pay'
  
  get '/useraccount/welcome' => 'useraccount#welcome'
  get '/useraccount/userorders' => 'useraccount#userorders'
  get '/useraccount/userorders/:id' => 'useraccount#ordershow'
  
  get '/admin' => 'useraccount#admin_welcome'
  get '/users' => 'useraccount#admin_users'
  get '/upgradeadmin/:id' => 'useraccount#upgrade_admin'
  get '/downgradeadmin/:id' => 'useraccount#downgrade_admin'
  delete '/removeuser/:id' => 'useraccount#remove'
  get '/reviews' => 'useraccount#all_reviews'
  get '/useraccount/reviews' => 'useraccount#user_reviews'
  
  post '/wishlist/add/:id' => 'wishlistitems#add'
  get '/wishlist/add/:id' => 'wishlistitems#add'
  get '/wishlist' => 'wishlistitems#index'
  delete '/wishlist/:id' => 'wishlistitems#destroy'

  
  get '/payment' => 'orders#pay'
  post '/payment' => 'orders#pay'


  



 
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/controllers/useraccount_controller.rb
class UseraccountController < ApplicationController
 before_action :authenticate_user!
 before_action :admin_user, only: [:admin_welcome, :admin_users, :upgrade_admin, :downgrade_admin, :remove, :all_reviews]
 before_action :set_user, only: [:upgrade_admin, :downgrade_admin, :remove]
     
    def welcome
        @recentview = Recentlyviewed.where(user_id: current_user.id)
    end
    
    def userorders
        @orders = Order.where(user_id: current_user.id)
    end
    
    def ordershow
        @order = Order.find(params[:id])
        if current_user.id != @order.user_id
            flash.now[:notice] = "Access Denied"
             redirect_to root_path
        end
        @orderitems = Orderitem.where(order_id: params[:id])
    end
    
    def user_reviews
        @reviews = Review.where(user_id: current_user.id)
    end
    
    def admin_welcome
        @items = Item.all
    end
    
    def admin_users
        @users = User.all
    end
    
    def upgrade_admin
        @user.update_attribute(:adminrole, true)
        redirect_to :action => :admin_users
    end
    
    def downgrade_admin
       @user.update_attribute(:adminrole, false)
       flash.now[:success] = "Admin premission removed"
       redirect_to :action => :admin_users
    end    
    
    def remove
        @user.destroy
        respond_to do |format|
          format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
          format.json { head :no_content }
        end
     
    end  
    
    def all_reviews
        @reviews = Review.all
    end
    
    def manage_stock
        @items = Item.all
    end
    
private
 #this method checks it the current user is admin - it is called before allowing access to certain areas/methods
    def admin_user
      if user_signed_in? && current_user.adminrole?
        flash.now[:success] = "Admin Access Granted"
      else
       redirect_to root_path
      end
    end
 
    def set_user
        @user = User.find(params[:id])
    end
    
    
end

app/helpers/useraccount_helper.rb
module UseraccountHelper
end

app/views/useraccount/_recentview.html.erb
<div class="container-fluid"><!-- container to hold all products-->
<% if @recentview == nil %>
<% else %>
<h5 class="text-center">Recently Viewed</h5>
    <div class="row">
        <div class="col-sm-1"></div>
         <% @recentview.limit(5).order(created_at: :desc).each do |item| %>
         <div class="col-sm-2">
            <div class="card">
                <img src="<%= item.item.image.url (:medium) %>" class="card-img-top jw-img-bestselling" />
              <div class="card-body">
                <a href="/items/<%= item.item.id %>" class="btn btn-block btn-secondary"><%= number_to_currency(item.item.price, :unit => "€") %></a>
              </div>
            </div>
        </div>
      <% end %> 
    </div>
<% end %>
</div>

app/views/useraccount/_useraccountnav.html.erb
<div class="container-fluid account-container">
    <div class="row justify-content-center">
        
        <div class="col-12 text-center">
            <a href="/useraccount/welcome" class="btn btn-secondary">Account</a>
            <a href="/useraccount/userorders" class="btn btn-secondary">Orders</a>
           <%= link_to 'Update Profile', edit_user_registration_path, :class => "btn btn-secondary" %>
           <a href="/wishlist" class="btn btn-secondary">Wishlist</a>
        </div>
        
    </div>
</div>

app/views/useraccount/admin_users.html.erb
<% provide(:title, "Admin") %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Id</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <% if user.adminrole == true %>
          <td>Admin</td>
        <% else %>
          <td>Customer</td>
        <% end%>
        
       
        <td><%#= link_to 'Show', user %></td>
        <td><%#= link_to 'Edit', edit_user_path(user) %></td>
        <td><%#s= link_to 'Destroy', user_registration_(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if user.adminrole == true %>
        <td><a href="/downgradeadmin/<%= user.id %>" class="btn btn-secondary" data-confirm='Are you sure?'>Remove Admin</a></td>
        <% else %>
        <td><a href="/upgradeadmin/<%= user.id %>" class="btn btn-secondary" data-confirm='Are you sure?'>Make Admin</a></td>
        <% end %>
        <td><a href="/removeuser/<%= user.id %>" class="btn btn-secondary" data-method="delete" data-confirm='Are you sure?'>Delete User</a></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/useraccount/admin_welcome.html.erb
<% provide(:title, "Admin") %>

<% if current_user.try(:adminrole?) %>


<div class="container-fluid account-container">
    <div class="row justify-content-center">
        
        <div class="col-12 text-center">
            <a href="/orders" class="btn btn-secondary">View Orders</a>
            <a href="/users" class="btn btn-secondary">Users</a>
            <a href="/reviews" class="btn btn-secondary">Reviews</a>
        </div>
        
    </div>
</div>


<h1>Items</h1>
<%= link_to 'New Product', new_item_path, :class => "btn btn-secondary", :role => "button" %>
<table class="table">
  
  <thead>
    <tr>
      <th>Item</th>
      <th></th>
      <th>Item Id</th>
      <th>Category</th>
      <th>Collection</th>
      <th>Created</th>
      <th>In Stock</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= image_tag item.image.url (:thumb) %></td>
        <td><%= item.title %></td>
        <td><%= item.id %></td>
        <td><%= item.category %></td>
        <td><%= item.collection %></td>
        <td><%= item.created_at %></td>
        <td><%= item.quantity_instock %></td>
        <td><%= item.quantity_sold %></td>
        
        <td><a href="/items/<%= item.id %>" class="btn btn-secondary"><i class="fa fa-eye"></i></a></td>
        <td><a href="/items/<%= item.id %>/edit" class="btn btn-secondary"><i class="fa fa-edit"></i></a></td>

        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-secondary", :role => "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>




<% end %>

app/views/useraccount/all_reviews.html.erb
<% provide(:title, "Admin") %>

<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table class="table">
  <thead>
    <tr>
      <th>Item</th>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.item %></td>
        <td><%= review.user %></td>
        <td><%= review.title %></td>
        <td><%= review.description %></td>
        <td><%= review.rating %></td>
        <td><a href="/items/<%=review.item.id%>/reviews/<%=review.id%>" data-method="delete" data-confirm='Are you sure?'>Delete</a>
        <%#= link_to 'Destroy', item_review_path(review), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Review', new_review_path %>

app/views/useraccount/manage_stock.html.erb
<% provide(:title, "Admin Stock") %>

<p id="notice"><%= notice %></p>

<h1>Items</h1>
<%= link_to 'New Product', new_item_path, :class => "btn btn-secondary", :role => "button" %>
<table class="table">
  
  <thead>
    <tr>
      <th>Item</th>
      <th></th>
      <th>Item Id</th>
      <th>Created</th>
      <th>In Stock</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= image_tag item.image.url (:thumb) %></td>
        <td><%= item.title %></td>
        <td><%= item.id %></td>
        <td><%= item.created %></td>
        <td><%= item.quantity_instock %></td>
        <td><%= item.quantity_sold %></td>
        
        <td><a href="/items/<%= order.id %>" class="btn btn-secondary"><i class="fa fa-eye"></i></a></td>
        <td><a href="/items/<%= item.id %>/edit" class="btn btn-secondary"><i class="fa fa-edit"></i></a></td>

        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-secondary", :role => "button" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/useraccount/ordershow.html.erb
<% provide(:title, "Order") %>

<div class="row justify-content-center">
    <%= render 'useraccount/useraccountnav'%> 
</div>



<!--show items in the order-->



    <table class ="table">
      <thead>
        <h1>Items in this order</h1>
      </thead>
      
      <thead>
        <th>Item</th>
        <th>Item Price</th>
        <th>Quantity</th>
        <th>Subtotal</th>
      </thead>
      <% total = 0 %>
      <% @orderitems.each do |orderitem| %>
      <tr>
        <td><%= orderitem.title %></td>
        <td><%= number_to_currency(orderitem.price, :unit => "€") %></td>
        <td><%= orderitem.quantity %></td>
        <% subtotal= orderitem.price * orderitem.quantity %>
        <td><%= number_to_currency(subtotal, :unit => "€") %></td>
        

        <% if Review.exists?(:user_id => current_user.id, :item_id => orderitem.item_id) %>
        <td><%= link_to 'See your Reviews', useraccount_reviews_path,  :class => "btn btn-secondary" %></td>
         <% else %>
         <td><%= link_to 'Add Review', new_item_review_path(orderitem.item_id), :class => "btn btn-secondary" %></td>
        <% end %>
        
      </tr>
      <% end %>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <% shipping = 5.95 %>
        <td>Shipping : <%= number_to_currency(shipping, :unit => "€") %></td>
      </tr>
      <tr>
        <td></td>
        <td></td>
        <td></td>
        <td>Order Total: <%= number_to_currency(@order.order_total, :unit => "€") %></td>
      </tr>
    </table>
 

</div>

app/views/useraccount/user_reviews.html.erb
<% provide(:title, "Admin") %>

<div class="row justify-content-center">
    <%= render 'useraccount/useraccountnav'%> 
</div>


<div class="row justify-content-center">
<% if @reviews %>

<h1><%=current_user.username%>'s Orders</h1>
</div>
<div class="row justify-content-center">
<table>
  <thead>
    <tr>
      <th>Review Title</th>
      <th>Description</th>
      <th>Item</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.description %></td>
        <td><%= review.item.title %></td>
        <td><%= link_to 'Edit', edit_item_review_path(review.item, review), :class =>"btn btn-secondary" %></td>
        
       

      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
</div>

app/views/useraccount/userorders.html.erb
<% provide(:title, "Account Orders") %>

<div class="row justify-content-center">
    <%= render 'useraccount/useraccountnav'%> 
</div>


<div class="row justify-content-center">
<% if @orders %>

<h1><%=current_user.username%>'s Orders</h1>
</div>
<div class="row justify-content-center">
<table>
  <thead>
    <tr>
      <th>Order date</th>
      <th>Status</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_date %></td>
        <td><%= order.status %></td>
        <td><%= order.order_total %></td>
        <td><a href="/useraccount/userorders/<%=order.id%>">See Order</a></td>
       

      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
</div>

app/views/useraccount/welcome.html.erb
<% provide(:title, "Account Welcome") %>
<div class="container-fluid ">
    <div class="row justify-content-center">
       <%= render 'useraccount/useraccountnav'%> 
    </div>
    <div class="row justify-content-center">
        <h1>Welcome <%=current_user.username%></h1>
        
        <%# if request.query_parameters["action"] == "orders" %>
        <%#= render :partial => 'orders/user_orders', :controller => "orders", :action => "orders_user_orders" %>  
        <%# end %>
        <%# if request.query_parameters["action"] == "edit" %>
        <%#= render :partial => 'users/registrations/edit', :controller => "users/registrations", :action => "edit" %>
        <%#= render :partial => 'cart/total', :controller => "cart", :action => "cart_header_info" %>
        <%# end %>
    
    </div>
    <div class="row justify-content-center">
        <%= render :partial => 'useraccount/recentview' %>
    </div>
        
</div>